In [1]:
import numpy as np

# Q1. Convert the given list in to a numpy array and replace the odd elements with -2.
### Lst = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
def solution_1():
    Lst = [[1,2,3], [4,5,6], [7,8,9]]
    arr = np.array(Lst)
    arr = np.where(arr & 1, -2, arr)
    print(arr)

In [9]:
solution_1()

[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


# Q2. In the numpy array given below print all the elements ranging from 8 to 15.
### arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]

In [20]:
def solution_2():
    arr = np.array([1,2,3,4,5,8,9,10,12,22,32,54,99,6,7])
    print(arr[7:16])

In [21]:
solution_2()

[10 12 22 32 54 99  6  7]


# Q3. Create a 3*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2.

In [22]:
def solution_3():
    arr = np.arange(1,10).reshape(3,3)
    arr[:,[0, 1]] = arr[:,[1, 0]]
    print(arr)

In [23]:
solution_3()

[[2 1 3]
 [5 4 6]
 [8 7 9]]


# Q4. In the given numpy array replace the NaN values with the average of columns.
### arr = np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])

In [34]:
def solution_4():
    arr = np.array(
        [
            [1.3, 2.5, 3.6, np.nan],
            [2.6, 3.3, np.nan, 5.5],
            [2.1, 3.2, 5.4, 6.5]
        ]
    )
    col_mean = np.nanmean(arr, axis=0)
    arr = np.where(np.isnan(arr), col_mean, arr)
    print(arr)

In [35]:
solution_4()

[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


# Q5. For the numpy array given below perform the following operation:
## i. Convert the numpy array into a numpy matrix
## ii. Sort the values in a matrix
### arr = [[2,4,6],[1,3,5]]

In [36]:
def solution_5():
    arr = np.array([[2,4,6],[1,3,5]])
    matrix = np.mat(arr)
    matrix = np.sort(matrix)
    print(matrix)

In [37]:
solution_5()

[[2 4 6]
 [1 3 5]]
